cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    
    path('', views.view_cart, name='view-cart'),
    path('add/<int:pk>/', views.add_item, name='add-item'),
    path('remove/<int:pk>/', views.remove_item, name='remove-item'),
    path('order-confirmed/', views.order_confirmed, name='order-confirmed'),
    path('clear-cart/', views.clear_cart, name='clear-cart')
]

final_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('market.urls')),
    path('news/', include('news.urls')),
    path('cart/', include('cart.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), 
         name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), 
         name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), 
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from market.models import Product
# Create your models here.


#Model to help display the relevant item in a users cart
class CheckoutItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    weight = models.PositiveIntegerField(default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.weight}g x {self.product.name}' 

    @classmethod
    def clear_cart(cls, user):
        """Clear all items in the cart for the given user."""
        cls.objects.filter(user=user).delete()

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import CheckoutItem
from market.models import Product
from market.utils import final_metal_price
from decimal import Decimal
from django.contrib import messages
# Create your views here.


# View to display all the items in the a users cart
def view_cart(request):
    checkout_items = CheckoutItem.objects.filter(user=request.user)

   
    cart_items = [
        {
            'pk' : item.pk,
            'product': item.product,
            'weight': item.weight,
            'metal_price': final_metal_price(item.product, request.user), # An metals price per g
            'total_price': final_metal_price(item.product, request.user) * item.weight # Metal price * weight
        }
        for item in checkout_items
    ]

    
    final_price = sum(item['total_price'] for item in cart_items)
    vat_price = final_price * (Decimal(1.23)) #Price with Irish VAT

    vat_price = vat_price.quantize(Decimal('0.01')) # Shorten result to two decimal places

   
    context = {
        'checkout_items': cart_items,
        'final_price': final_price,
        'vat_price': vat_price,
    }

    return render(request, 'cart/checkout.html', context)

# View that adds particular metal to the cart at the requested weight in grams
def add_item(request, pk):
    if not request.user.is_authenticated: #To avoid checkout error / user must be logged in.
        messages.warning(request, f'You must be logged in to access the market')
        return redirect('login')
    product = Product.objects.get(pk=pk)
    weight = request.GET.get('weight', 1)
    
    checkout_item, created = CheckoutItem.objects.get_or_create(product=product,user=request.user)
    checkout_item.weight += Decimal(weight)
    checkout_item.save()
    return redirect('cart:view-cart')


# View that delets item from cart / Contained within 'X' icon.
def remove_item(request, pk):
    checkout_item = get_object_or_404(CheckoutItem, pk=pk, user=request.user)
    checkout_item.delete()
    return redirect('cart:view-cart')

# View that functions like the 'view_cart' view in order to simulate an order confirmed screen
def order_confirmed(request):
    checkout_items = CheckoutItem.objects.filter(user=request.user)

   
    cart_items = [
        {
            'pk' : item.pk,
            'product': item.product,
            'weight': item.weight,
            'metal_price': final_metal_price(item.product, request.user),
            'total_price': final_metal_price(item.product, request.user) * item.weight
        }
        for item in checkout_items
    ]

    
    final_price = sum(item['total_price'] for item in cart_items)
    vat_price = final_price * (Decimal(1.23)) #Price with Irish VAT

    vat_price = vat_price.quantize(Decimal('0.01'))

   
    context = {
        'checkout_items': cart_items,
        'final_price': final_price,
        'vat_price': vat_price,
    }

    
    return render(request,'cart/order_confirmed.html', context)

# Clears to whole cart after exiting the order confirmed screen
def clear_cart(request):
    """View to clear the user's cart and redirect to the product page."""
    CheckoutItem.objects.filter(user=request.user).delete() 
    return redirect('all-products') 

cart/templates/cart/checkout.html
{% extends "market/base.html" %}
{% block content %}
<h2>My Cart</h2>
<ul class="cart-product-list">
    {% for item in checkout_items %}
    <li class="cart-product-item">
        <img class="cart-product-image" src="{{ item.product.image.url }}" alt="{{ item.product.name }}">
        <div class="cart-product-info">
            <h3>{{ item.product.name }}</h3>

            {% if item.metal_price %}
            <p>{{ item.product.metal_type|title }} price per (g): €{{ item.metal_price }}/g</p>
            <p>Amount in Cart: {{ item.weight }}/g</p>
            {% else %}
            <p>Error.</p>
            {% endif %}
            <p class="product-price">€{{item.total_price}}</p>
        </div>
        <a class="remove-item" href="{% url 'cart:remove-item' item.pk %}">
            <i class="fas fa-times"></i>
        </a>

    </li>
    {% endfor %}
</ul>
<div class="final-price">
    <h3>Final Price</h3>
    <p class="product-price">€{{ vat_price }} inc.VAT</p>
    <p class="price-no-vat">€{{ final_price }} exc.VAT</p>
</div>
<div class="cart-buttons">
    <a href="{% url 'all-products' %}" class="btn btn-secondary">Continue Shopping</a>
    <a href="{% url 'cart:order-confirmed'%}" class="btn btn-primary">Pay Now</a>
</div>
{% endblock content %}

cart/templates/cart/order_confirmed.html
{% extends "market/base.html" %}
{% block content %}
<h2>Order Confirmed</h2>

<p>Thank you for your purchase! Your order is on its way.</p>
<ul class="cart-product-list">
    {% for item in checkout_items %}
    <li class="cart-product-item">
        <img class="cart-product-image" src="{{ item.product.image.url }}" alt="{{ item.product.name }}">
        <div class="cart-product-info">
            <h3>{{ item.product.name }}</h3>

            {% if item.metal_price %}
            <p>{{ item.product.metal_type|title }} price per (g): €{{ item.metal_price }}/g</p>
            <p>Amount in Cart: {{ item.weight }}/g</p>
            {% else %}
            <p>Error.</p>
            {% endif %}
            <p class="product-price">€{{item.total_price}}</p>
        </div>

    </li>
    {% endfor %}
</ul>

<div class="final-price">
    <h3>Final Price</h3>
    <p class="product-price">€{{ vat_price }} inc. VAT</p>
    <p class="price-no-vat">€{{ final_price }} exc. VAT</p>
</div>

<div class="cart-buttons">
    <!-- Button to continue shopping and clear the cart -->
    <form method="post" action="{% url 'cart:clear-cart' %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-secondary">Continue Shopping</button>
    </form>
</div>
{% endblock content %}