cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    
    path('', views.view_cart, name='view-cart'),
    path('add/<int:pk>/', views.add_item, name='add-item'),
    path('remove/<int:pk>/', views.remove_item, name='remove-item'),
    path('order-confirmed/', views.order_confirmed, name='order-confirmed'),
    path('clear-cart/', views.clear_cart, name='clear-cart')
]

final_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('market.urls')),
    path('news/', include('news.urls')),
    path('cart/', include('cart.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), 
         name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), 
         name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), 
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

market/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path ("", views.home, name='market-home'),
    path ("about/", views.about, name='market-about'),
    path ("product/", views.product, name='market-product'),
    path ("product/<int:product_id>/", views.product, name='product'),
    path ("all-products/", views.all_products, name='all-products'),
]   

market/models.py
from django.db import models

# Create your models here.


# A model where the current and historical prices are stored
class CurrentMetalPrice(models.Model):
    date = models.DateField(auto_now_add=True)
    gold_price = models.DecimalField(max_digits=20, decimal_places=10, null=True, blank=True)
    silver_price = models.DecimalField(max_digits=20, decimal_places=10, null=True, blank=True)
    platinum_price = models.DecimalField(max_digits=20, decimal_places=10, null=True, blank=True)
    palladium_price = models.DecimalField(max_digits=20, decimal_places=10, null=True, blank=True)

    def __str__(self):
        return f"Metal prices for {self.date}"
    


# A model that helps display the relevant information about a selected product
class Product(models.Model):

    METALS = [
        ('gold', 'Gold'),
        ('silver', 'Silver'),
        ('platinum', 'Platinum'),
        ('palladium', 'Palladium'),
    ]



    name = models.CharField(max_length=255)
    blurb = models.TextField(max_length=20)
    description = models.TextField()
    image = models.ImageField(upload_to='products/')
    weight = models.CharField(max_length=100)
    color = models.CharField(max_length=100)
    country_of_origin = models.CharField(max_length=100)
    density = models.CharField(max_length=100)
    melting_range = models.CharField(max_length=100)
    metal_type = models.CharField(max_length=10, choices=METALS, default='gold')

    def __str__(self):
        return self.name

market/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product
import logging
from .utils import final_metal_price

# Create your views here.

logger = logging.getLogger(__name__)

def home(request):
    products = Product.objects.all()
    return render(request, 'market/home.html', {'products': products})

def about(request):
    return render (request, 'market/about.html')

#View that displays a given product using pk id and the matching metal price
def product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    metal_price = final_metal_price(product, request.user)

    logger.debug(f"Product: {product.name}, Metal Type: {product.metal_type}, Metal Price: {metal_price}")

    context = {
        'product': product,
        'metal_price': metal_price,
    }
    return render(request, 'market/product.html', context)

# View that displays a list of all the products. Seperate from the list seen on the homepage.

def all_products(request):
    products = Product.objects.all()
    product_list = [
        {
            'product': product,
            'metal_price': final_metal_price(product, request.user)
        }
        for product in products
    ]

    return render(request, 'market/all_products.html', {'product_list': product_list})

market/templates/market/about.html
{% extends "market/base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <div class="about-section">
        <h2 class="about-title">About Precious Metals</h2>
        <p class="about-blurb">At Precious Metals, we offer you a trusted platform to buy gold,
            silver, platinum, and palladium at today's market prices.
            Whether you're an investor, collector, or simply looking to diversify your portfolio, our site provides the
            most
            up-to-date prices,
            ensuring you get the best value for your purchase.</p>

        <p class="about-blurb">Stay informed with the latest trends and insights in the precious metals market through
            our regularly updated
            news section. From market analyses to industry developments, we provide the information you need to make
            informed decisions.

            Join us at Precious Metals, where value meets security, and stay ahead in the world of precious metals.</p>
    </div>

    <section id="faq-section">
        <h2 id="faq-title">FAQ</h2>

        <div class="faq">
            <div class="question-container">
                <h3 class="question-title">What metals can I buy on Precious Metals?</h3>

                <svg width="1.75em" height="1.75em" viewBox="0 0 17 17" version="1.1" xmlns="http://www.w3.org/2000/svg"
                    xmlns:xlink="http://www.w3.org/1999/xlink">
                    <path d="M16.354 5.075l-7.855 7.854-7.853-7.854 0.707-0.707 7.145 7.146 7.148-7.147 0.708 0.708z"
                        fill="#000000" />
                </svg>
            </div>
            <div class="answer-container">
                <p class="answer">
                    On Precious Metals, you can purchase a wide variety of metals, including gold, silver,
                    platinum, and palladium. We offer these metals in various forms, such as coins, bars, and bullion,
                    allowing you to choose the type that best suits your investment needs.

                </p>
            </div>
        </div>

        <div class="faq">
            <div class="question-container">
                <h3 class="question-title">How does Precious Metals ensure I get the best prices?</h3>

                <svg width="1.75em" height="1.75em" viewBox="0 0 17 17" version="1.1" xmlns="http://www.w3.org/2000/svg"
                    xmlns:xlink="http://www.w3.org/1999/xlink">
                    <path d="M16.354 5.075l-7.855 7.854-7.853-7.854 0.707-0.707 7.145 7.146 7.148-7.147 0.708 0.708z"
                        fill="#000000" />
                </svg>
            </div>
            <div class="answer-container">
                <p class="answer">
                    Precious Metals provides real-time pricing based on current market conditions. We continuously
                    monitor the market to ensure our prices reflect the most accurate and up-to-date values. This way,
                    you can be confident that you're getting the best value for your purchases.

                </p>
            </div>
        </div>

        <div class="faq">
            <div class="question-container">
                <h3 class="question-title">How often is the news section updated?</h3>

                <svg width="1.75em" height="1.75em" viewBox="0 0 17 17" version="1.1" xmlns="http://www.w3.org/2000/svg"
                    xmlns:xlink="http://www.w3.org/1999/xlink">
                    <path d="M16.354 5.075l-7.855 7.854-7.853-7.854 0.707-0.707 7.145 7.146 7.148-7.147 0.708 0.708z"
                        fill="#000000" />
                </svg>
            </div>
            <div class="answer-container">
                <p class="answer">
                    Our news section is updated weekly (sometimes more) with the latest trends, analyses, and insights from the precious
                    metals market. Whether you're tracking market movements or seeking expert opinions, our news section
                    provides the information you need to stay informed and make educated decisions.

                </p>
            </div>
        </div>
    </section>
</div>

<script src="{% static 'market/js/collapse.js' %}"></script>

{% endblock %}

market/templates/market/all_products.html
{% extends "market/base.html" %}
{% block content %}
<h2>All Products</h2>
<ul class="all-products-list">
    {% for item in product_list %}

    <li class="all-products-item">

        <a href="{% url 'product' item.product.id %}">
            <img class="all-products-img" src="{{ item.product.image.url }}" alt="{{ item.product.name }}">
        </a>
        <div>
            <a href="{% url 'product' item.product.id %}">
                <h3>{{ item.product.name }}</h3>
            </a>
            <p>{{ item.product.description }}</p>
            {% if item.metal_price %}
            <p>{{ item.product.metal_type|title }}, price/(g):</p>
            <p class="product-price"> €{{ item.metal_price }}/g</p>
            {% else %}
            <p>Error.</p>
            {% endif %}
        </div>
        <a class="product-link" href="{% url 'product' item.product.id %}">More Info</a>
    </li>
    {% endfor %}
</ul>
{% endblock content %}

market/templates/market/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <!-- Custom CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'market/css/style.css' %}">
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/0f9f99c030.js" crossorigin="anonymous"></script>


  {% if title %}
  <title> Precious Metals - {{ title }} </title>
  {% else %}
  <title> Precious Metals </title>
  {% endif %}


</head>

<body class="container">

  <header class="site-header">
    <nav class="navbar navbar-expand-lg navbar-dark">
      <div class="container">

        <!-- Site Title w/ Icon-->
        <a class="navbar-brand" href="{% url 'market-home' %}">
          <i class="fas fa-gem"></i>
          Precious Metals
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav ml-auto">
            <!-- Main Navbar -->
            <a class="nav-item nav-link" href="{% url 'market-home' %}">
              Home
            </a>
            <a class="nav-item nav-link" href="{% url 'all-products' %}">
              Shop
            </a>
            <a class="nav-item nav-link" href="{% url 'news-page' %}">
              News
            </a>
            <a class="nav-item nav-link" href="{% url 'market-about' %}">
              About
            </a>
          </div>

          <!-- Login / My Profile Navbar-->

          <div class="navbar-nav">
            {% if user.is_authenticated %}

            <a class="nav-item nav-link nav-item-alt-1" href="{% url 'profile' %}">Account</a>
            <a class="nav-item nav-link nav-item-alt-2" href="{% url 'cart:view-cart' %}">Checkout</a>
            <form method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <button type="submit" class="nav-item nav-link nav-item-alt-1">Logout</button>
            </form>

            {% else %}

            <a class="nav-item nav-link nav-item-alt-1" href="{% url 'login' %}">
              Login
            </a>
            <a class="nav-item nav-link nav-item-alt-2" href="{% url 'register' %}">
              Register
            </a>

            {% endif %}
          </div>
        </div>

      </div>
    </nav>
  </header>
  <main>
    <div>
      <div>
        {% if messages %}
        <div class="alert alert-warning">
          {% for message in messages %}
          <p>{{ message }}</p>
          {% endfor %}
        </div>
        {% endif %}
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </main>
  <!--Imported Scripts-->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <!-- Custom Script-->
  <script src="{% static 'market/js/active.js' %}"></script>
</body>
<!-- Footer -->
<footer class="text-center text-lg-start bg-body-tertiary">


  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <div class="d-flex justify-content-center justify-content-lg-between p-4">

            <div>
              <a href="#" class="me-4 text-decoration-none text-reset">
                <i class="fab fa-facebook-f"></i>
              </a>
              <a href="#" class="me-4 text-decoration-none text-reset">
                <i class="fa-brands fa-x-twitter"></i>
              </a>
              <a href="#" class="me-4 text-decoration-none text-reset">
                <i class="fab fa-google"></i>
              </a>
              <a href="#" class="me-4 text-decoration-none text-reset">
                <i class="fab fa-instagram"></i>
              </a>
              <a href="#" class="me-4 text-decoration-none text-reset">
                <i class="fab fa-linkedin"></i>
              </a>
              <a href="#" class="me-4 text-decoration-none text-reset">
                <i class="fab fa-github"></i>
              </a>
            </div>

          </div>
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Precious Metals
          </h6>
          <p>
            Join us at Precious Metals, where value meets security, and stay ahead in the world of precious metals.
          </p>
        </div>



        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="{% url 'all-products'%}" class="text-reset">All Products</a>
          </p>
          <p>
            <a href="{% url 'product' 1 %}" class="text-reset">18ct Yellow</a>
          </p>
          <p>
            <a href="{% url 'product' 2 %}" class="text-reset">9ct Yellow</a>
          </p>
          <p>
            <a href="{% url 'product' 3 %}" class="text-reset">Silver</a>
          </p>
          <p>
            <a href="{% url 'product' 4 %}" class="text-reset">Platinum</a>
          </p>
          <p>
            <a href="{% url 'product' 5 %}" class="text-reset">Palladium</a>
          </p>
          <p>
            <a href="{% url 'product' 6 %}" class="text-reset">Fine Gold</a>
          </p>
        </div>

        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="{% url 'news-page'%}" class="text-reset">News</a>
          </p>
          <p>
            <a href="{% url 'profile' %}" class="text-reset">Account</a>
          </p>
          <p>
            <a href="{% url 'cart:view-cart' %}" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="{% url 'market-about' %}" class="text-reset">FAQ</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> Dublin 2, Ireland</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            davidwebtesting@gmail.com
          </p>
          <p><i class="fas fa-phone me-3"></i> +353 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> +353 01 234 567 89</p>
        </div>

      </div>

    </div>
  </section>


  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2024 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">David Sexton</a>
  </div>

</footer>


</html>

market/templates/market/home.html
{% extends "market/base.html" %}
{% block content %}

<!--Welcome Banner-->
<section id="welcome-banner" class="text-center bg-image"
    style="background-image:url('https://django-module5.s3.eu-north-1.amazonaws.com/metal-banner.jpg');">


    <div class="mask d-flex justify-content-center align-items-center h-100">
        <div>

            <h2 class="mb-3">
                Welcome to Precious Metals!
            </h2>
            <p class="mb-3">Ireland's No.1 Provider of Bullion</p>

            {% if user.is_authenticated %}

            <a data-mdb-ripple-init class="btn btn-outline-light btn-lg m-2" href="{% url 'all-products' %}" role="button">Shop</a>

            {% else %}

            <a data-mdb-ripple-init class="btn btn-outline-light btn-lg m-2" href="{% url 'register' %}"
                role="button">Sign Up</a>
            <a data-mdb-ripple-init class="btn btn-outline-light btn-lg m-2" href="{% url 'login' %}"
                role="button">Login</a>

            {% endif %}

        </div>
    </div>


</section>


<section class="d-flex align-items-center h-100 home-product-container">
    <div>
        <h2>
            All Metals
        </h2>
        <p>Buy Now</p>
    </div>
    <div class="home-product-list">
        {% for product in products %}
        <a href="{% url 'product' product.id %}" id="{{ product.name|slugify }}" class="home-product-item">
            <h3>{{ product.name }}</h3>
            <p>{{ product.blurb }}</p>
        </a>
        {% endfor %}
    </div>
</section>
<section class="newsletter-section">
    <div class="newsletter-div">
        <div>
            <h2>Follow the Latest Metal Trends</h2>
            <p>New Article Every Week</p>
        </div>
        <div>
            <form class="newsletter-form" method="post" action="{% url 'subscribe' %}">
                {% csrf_token %}
                <input class="newsletter-email" type="email" name="email" placeholder="user@example.com" required>
                <button class="newsletter-btn" type="submit">Subscribe</button>
            </form>
        </div>
    </div>
</section>


{% endblock %}

market/templates/market/product.html
{% extends "market/base.html" %}
{% block content %}

<section class="container product-page">
    <div>
        <div class="carousel-inner">
            <div>
                <div class="card">

                    <div class="row">
                        <div class="col-md-6 text-center align-self-center">
                            <img class="img-fluid product-img" src="{{ product.image.url }}" alt="{{ product.name }}">
                        </div>
                        <div class="col-md-6 info">
                            <div class="row title">
                                <div class="col">
                                    <h2>{{ product.name }}</h2>
                                    <p><span class="fa fa-star checked"></span>
                                        <span class="fa fa-star checked"></span>
                                        <span class="fa fa-star checked"></span>
                                        <span class="fa fa-star checked"></span>
                                        <span class="fa fa-star-half-full"></span>
                                        <span id="reviews">1590 Reviews</span>
                                    </p>

                                    {% if metal_price %}
                                    <p>{{ product.metal_type|title }}, price/(g):</p>
                                    <p class="product-price"> €{{ metal_price }}/g</p>
                                    {% else %}
                                    <p>Error.</p>
                                    {% endif %}
                                </div>
                                <div class="col text-right">
                                    <a href="#"><i class="fa fa-heart-o"></i>
                                    </a>
                                </div>
                            </div>



                            <div class="row">
                                <div class="col-md-6">
                                    <label for="amount-grams">Weight(g):</label>
                                    <input type="number" id="weight" name="weight" min="1" step="0.01"
                                        placeholder="min. 1(g)">


                                </div>
                                {% if user.is_authenticated %}
                                <div class="col text-right align-self-center">
                                    <a class="btn" href="{% url 'cart:add-item' product.pk %}?weight="
                                        onclick="this.href = this.href + document.getElementById('weight').value">Add to
                                        cart</a>
                                </div>
                                {% else %}
                                <div class="col text-right align-self-center">
                                    <a class="btn" href="{% url 'login' %}">Add to
                                        cart</a>
                                </div>
                                {% endif %}

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container mt-2 product-info">
            <div class="mr-4 product-blurb">
                <h3>Description</h3>
                <p>{{ product.description }}</p>
            </div>
            <div>
                <h3>Specifications</h3>
                <p><span>Product Weight:</span> {{product.weight}}</p>
                <p><span>Colour:</span> {{ product.color }}</p>
                <p><span>Country of Origin:</span> {{ product.country_of_origin }}</p>
                <p><span>Density:</span> {{ product.density }}</p>
                <p><span>Melting Range:</span> {{product.melting_range }}</p>
            </div>
        </div>
</section>




{% endblock %}